# Generated by Django 5.2.1 on 2026-01-02 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Event description/notes', null=True)),
                ('start_datetime', models.DateTimeField(help_text='Event start date and time')),
                ('end_datetime', models.DateTimeField(help_text='Event end date and time')),
                ('reminder_minutes', models.IntegerField(choices=[(5, '5 minutes before'), (10, '10 minutes before'), (30, '30 minutes before'), (60, '1 hour before'), (1440, '1 day before')], default=30, help_text='Reminder time before event')),
                ('reminder_triggered', models.BooleanField(default=False, help_text='Whether the reminder has been triggered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_event_id', models.CharField(blank=True, help_text='Google Calendar event ID for synchronization', max_length=255, null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['created_by', 'start_datetime'], name='events_even_created_f3202e_idx'), models.Index(fields=['reminder_triggered', 'start_datetime'], name='events_even_reminde_4bc5ff_idx')],
            },
        ),
    ]
