# Generated by Django 5.2.1 on 2026-01-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='google_event_id',
        ),
    ]
