# Generated by Django 5.2.1 on 2026-01-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID for synchronization', max_length=255, null=True),
        ),
    ]
